name: Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get install -y libsodium-dev libssl-dev libcrypto++-dev

    - name: Install vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
        .\vcpkg install libsodium openssl crypto++

    - name: Setup CMake
      uses: lukka/get-cmake@latest

    - name: Configure project
      run: |
        mkdir build
        cd build
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          cmake .. -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release
        else
          cmake .. -DCMAKE_BUILD_TYPE=Release
        fi
      shell: bash

    - name: Build project
      run: |
        cd build
        cmake --build . --parallel 4

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
