name: Build and Test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: papasitory/messenger-e2ee-module
        token: ${{ secrets.GITHUB_TOKEN }}
        ssh-strict: true
        persist-credentials: true
        clean: true
        fetch-depth: 1
        fetch-tags: false
        lfs: false
        submodules: false

    - name: Configure Git safe.dir (Windows)
      if: runner.os == 'Windows'
      run: git config --global --add safe.directory "${{ github.workspace }}"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        check-latest: true

    - name: Install dependencies
      run: npm install -g typescript

    - name: Build project
      run: tsc

#    - name: Run project
#      run: node dist/index.js
